
version: "3.9"

services:
  rpnapi:
    build:
      context: rpn_api
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/postgres
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
