version: "3.9"

services:
  rpnapi:
    build:
      context: rpn_api
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/postgres
    depends_on:
      - db

    dp:
      image: postgres:13
